### ISSUE TITLE
Could not resolve ro.andob.androidawt:androidawt:1.0.4

### ISSUE THREAD

**Issue by emanonw1991** [andob/android-awt#11]
i import android-awt by maven, but fail to build my project with error below:

* What went wrong:
Execution failed for task ':common_base:dataBindingMergeDependencyArtifactsDebug'.
> Could not resolve all files for configuration ':common_base:debugCompileClasspath'.
   > Could not find :androidawt-1.0.4:.
     Required by:
         project :common_base > project :lib_base
   > Could not resolve ro.andob.androidawt:androidawt:1.0.4.
     Required by:
         project :common_base > project :lib_base
      > Could not resolve ro.andob.androidawt:androidawt:1.0.4.
         > Could not get resource 'https://maven.andob.info/repository/open_source/ro/andob/androidawt/androidawt/1.0.4/androidawt-1.0.4.pom'.
            > Could not GET 'https://maven.andob.info/repository/open_source/ro/andob/androidawt/androidawt/1.0.4/androidawt-1.0.4.pom'.
               > PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

i googled this error, and guess it might be certificate problem with maven repository. can u please fix this?

**Comment by andob** [comment]
@emanonw1991 seems like there was a downtime on either Let's Encrypt or the hosting service.
please try again.
