### ISSUE TITLE
Conflicts: Nonnull, Nullable and ParametersAreNonnullByDefault

### ISSUE THREAD

**Issue by hurzl** [andob/android-awt#3]
Probably since androidx these class definitions are too much

```
Duplicate class javax.annotation.Nonnull found in modules jetified-android-awt-1.0.1-runtime.jar (com.github.andob:android-awt:1.0.1) and jetified-jsr305-3.0.2.jar (com.google.code.findbugs:jsr305:3.0.2)
Duplicate class javax.annotation.Nullable found in modules jetified-android-awt-1.0.1-runtime.jar (com.github.andob:android-awt:1.0.1) and jetified-jsr305-3.0.2.jar (com.google.code.findbugs:jsr305:3.0.2)
Duplicate class javax.annotation.ParametersAreNonnullByDefault found in modules jetified-android-awt-1.0.1-runtime.jar (com.github.andob:android-awt:1.0.1) and jetified-jsr305-3.0.2.jar (com.google.code.findbugs:jsr305:3.0.2)
```
How can I avoid this?
I solved it now by manually removing these 3 classes from the jar.

**Comment by andob** [comment]
@hurzl solved. please import the latest version, 1.0.3

**Comment by andob** [comment]
@serxipc I saw you forked my repo and did [a commit](https://github.com/serxipc/android-awt/commit/83dbb2d852f906681f700a1a232692afd8cf5de2) to solve the same issue (with the same solution).
do you want to submit a pull request of your fork into my repo or do you want to leave them like that?

**Comment by serxipc** [comment]
@andob You can leave it as it is now. Thanks for letting me know
