### ISSUE TITLE
PrinterGraphics missing on Android

### ISSUE THREAD

**Issue by andreasrosdalw** [andob/android-awt#4]
PrinterGraphics is also missing on Android

https://github.com/LibrePDF/OpenPDF/issues/371

**Comment by Drakot** [comment]
Hi,
is there any news about this?

**Comment by andreasrosdalw** [comment]
Pull requests welcome.

**Comment by andob** [comment]
I don't know why PrinterGraphics and PrintJob would be needed, since Android has other mechanisms for printing.

@Drakot can you give me a code snippet / sample illustrating the issue? I need to replicate it.

**Comment by Drakot** [comment]
It only happen to me on a device that uses API 28, but i realized the library works the same.

**Comment by andob** [comment]
in OpenPDF, there's this class ``PdfPrinterGraphics2D`` that uses ``PrinterGraphics`` and ``PrinterJob``. It is only instantiated in these methods from ``PdfContentByte`` class:

![image](https://user-images.githubusercontent.com/5281358/107142738-98a5ff00-6939-11eb-8daf-e728ebe94565.png)

Yet none of these methods are used inside the OpenPDF project.

Make sure you're using the latest OpenPDF version,

```
implementation 'com.github.librepdf:openpdf:1.3.24'
```
