### ISSUE TITLE
Can I use this to make plantuml work on android?

### ISSUE THREAD

**Issue by sinojelly** [andob/android-awt#7]
plantuml depends on java.awt.

The project is here:
https://github.com/plantuml/plantuml

I tried to compile plantuml with android-awt, still too many dependencies can't be found.

See also:
https://github.com/plantuml/plantuml/issues/464

**Comment by andob** [comment]
no, too many dependencies, ant, swing, awt window + label and so on. this library was meant only as a replacement for the drawing awt classes (images, canvas, graphics2d, color, dimension, point, ...), not as a compatibility layer for the entire awt + swing UI toolkit.

Have you tried to install standard java (openjdk) in termux?

https://github.com/MasterDevX/Termux-Java
https://stackoverflow.com/questions/61720889/how-can-i-install-java-runtime-on-android-device

then run plantuml with something like ``java -jar plantuml.jar``.

also - have you tried this app https://play.google.com/store/apps/details?id=ru.gelin.android.plantuml&hl=en&gl=US ?
