### ISSUE TITLE
issue in add image to pdf in android

### ISSUE THREAD

**Issue by shambhu-sharan** [andob/android-awt#8]
image not showing in pdf .

**Comment by andob** [comment]
ok. can you give me example code and image?

**Comment by shambhu-sharan** [comment]
in gradle i have added 

 implementation 'com.github.librepdf:openpdf:1.3.25'
 implementation 'ro.andob.androidawt:androidawt:1.0.4'
 
 file path-->file:///storage/emulated/0/pdf/company_logo_0.jpg
 
Bitmap bitmap = BitmapFactory.decodeFile(file.getPath());
 ByteArrayOutputStream stream = new ByteArrayOutputStream();
 bitmap.compress(Bitmap.CompressFormat.PNG, 100, stream);
 Image image = Image.getInstance(stream.toByteArray());
 image.scaleAbsolute(100, 100);
 PdfPCell  cellImg = new PdfPCell(image, true);
 PdfPTable imgTable = new PdfPTable(1);
 imgTable.addCell(cellImg);
 
     
     
![images (1)](https://user-images.githubusercontent.com/21050428/111598348-24426380-87f5-11eb-8f7e-73a48745c00b.png)

**Comment by andob** [comment]
if it's not confidential, can you give me the exact file? upload it to google drive then send me a link usingvirtualbox@gmail.com

**Comment by andob** [comment]
I see that you are accesing the file path on non-scoped storage:
file:///storage/emulated/0/company_logo_0.jpg
non-scoped storage and write_external storage permissions are deprecated in latest Android versions and not a good practice.
is that ok??

have you tried to access it from
/storage/emulated/0/Android/your_package_name/files/company_logo_0.jpg
or
/data/data/your_package_name/files/pdf/company_logo_0.jpg

you can get those paths like this:
```
File dir = context.getExternalFilesDir(null);
File file = new File(dir, "company_logo_0.jpg");
///storage/emulated/0/Android/your_package_name/files/company_logo_0.jpg
```
or
```
File file = context.getFileStreamPath("company_logo_0.jpg");
///data/data/your_package_name/files/pdf/company_logo_0.jpg
```

**Comment by shambhu-sharan** [comment]
I have targeted api v 29 (scoped storage come on 29+)
and I have checked , I am getting file from storage, conversion to bitmap also ok . some png image display in pdf but most of image doesn't .

**Comment by andob** [comment]
ok, I'll take a look later today.

**Comment by andob** [comment]
- loading that image as PNG doesn't seem to work
- also loading ``Image.getInstance(bytes)`` doesn't seem to work, but it works if you do ``Image.getInstance(filePath)``

Try converting it into JPEG first:

```kotlin
        //convert to jpeg
        val bitmap=BitmapFactory.decodeFile(imageFile.absolutePath)
        FileOutputStream(imageFile).use { outputStream ->
            bitmap.compress(Bitmap.CompressFormat.JPEG, 100, outputStream)
        }

        val table=PdfPTable(1)
        val image=Image.getInstance(imageFile.absolutePath)
        image.scaleAbsolute(100.0f, 100.0f)
        val cell=PdfPCell(image, true)
        table.addCell(cell)
        pdf.add(table)
```
